server.port=${SERVER_PORT:8091}
grpc.server.port=${GRPC_SERVER_PORT:9091}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=3s

skinex.frontend.jwt.secret=${NEXTAUTH_SECRET:}
skinex.frontend.url=${FRONTEND_URL:http://localhost:3000}

# wiki: префикс ключей в Redis и TTL (0 — бессрочно, данные перезаливаются при старте)
pattern.redis.prefix=pattern
pattern.redis.ttl-ms=0

# Админ SteamID для ручной перезаливки
app.admin.steam-id=${ADMIN_STEAM_ID:76561199027967594}

spring.application.name=wiki

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p ${PID:-} --- [%15.15t] %-40.40logger{39} cid=%X{correlationId:-} : %m%n%wEx
